trigger: meeting_notes
title: Meeting Notes
description: Spawn up a template for notes. Great for multitasking SEs!
surfaces:
- issue
steps:
- type: form
  style: modal
  body:
  - type: input
    attributes:
      label: Title
      placeholder: POC Kick-Off Call...
  - type: input
    attributes:
      label: Attendees
      placeholder: @octocat, @mona, customer1, customer2...
  - type: textarea
    attributes:
      label: Notes
      placeholder: Organize this how you want
      value: - 
  - type: textarea
    attributes:
      label: NextSteps
      placeholder: Organize this how you want
      value: |
      @{{ command.user.login }}
      - [ ]
      @Rep
      - [ ]
  - type: markdown
    attributes:
      text: - [ ] TEST
