# Creates a template for note-taking. Call in an issue by typing "/meeting_notes" or "/notes"
# To save this command and use it across an repo on your GitHub profile go through the following steps:
# 1) Create a repo <USERNAME>/.github-private
# 2) Save this file under .github/commands/meeting-notes.yml

trigger: meeting_notes
title: Meeting Notes
description: Spawn a template for notes. Great for multitasking SEs!
surfaces:
- issue

steps:

# Create form for note-taking
- type: form
  style: embedded
  body:
  # Meeting Title Section
  - type: input
    attributes:
      label: Title
      placeholder: POC Kick-Off Call...
  # Attendees Section
  - type: input
    attributes:
      label: Attendees
      placeholder: "@octocat, @mona, customer1, customer2..."
  # Date Section
  - type: input
    attributes:
      label: Date
      format: date
  # Notes Section
  - type: textarea
    attributes:
      label: Notes
      placeholder: Organize this how you want
      value: "- "
  # Next Steps Section
  - type: textarea
    attributes:
      label: NextSteps
      description: Enter your action items first, and jot down those for a teammate as well.
      placeholder: Organize this how you want
      value: |
        - [ ] 
        
        @teammate
        - [ ] 

# Output notes from entered values
- type: fill
  template: |

    ## {{ data.Title }}
    **Date:** {{ data.Date }}

    **Attendees:** {{ data.Attendees }}

    ### Notes

    {{ data.Notes }}

    ### Next Steps
    
    @{{ command.user.login }}
    {{ data.NextSteps }}
