name: Push Issue to Project

# Testing stuff out over here when it comes to pushing

on:
  issues:
    types: [ assigned, labeled ]

  # workflow_dispatch:

jobs:
  add-to-project:
    runs-on: ubuntu-latest

    steps:
      - uses: Eldrick19/add-to-project@assignee-as-trigger
        with:
          project-url: https://github.com/users/Eldrick19/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: for-eldrick
