name: Assign to Project

on:
  issues:
    types: [ opened, assigned ]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: github.event.issue.assignee.name == 'eldrick19'
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          # You can target a repository in a different organization
          # to the issue
          project-url: https://github.com/orgs/github/projects/5572
          github-token: ${{ secrets.GITHUB_TOKEN }}
