# Used to auto-assign an issue creator
# A lot of integrations are depndent on issue assignmnets, want to make sure we're on top of it!

name: Auto Assign
on:
  issues:
    types: [ opened ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # using the `org/team_slug` or `/team_slug` syntax to add git team as reviewers
          addAssignees: 'author'
